export const data = [
    {
        name: 'Country',
        apiIdSingular: 'country',
        apiIdPlural: 'countries',
        groupName: '',
        relations: [
            {
                relationType: null,
                relationTable: null,
                isOneToMany: false,
                isManyToMany: false,
                isParent: true,
                isChild: false,
                parent: {
                    name: 'Country',
                    apiIdSingular: 'country',
                    apiIdPlural: 'countries',
                    groupName: '',
                    method: 'hasMany',
                },
                child: {
                    method: 'belongsTo',
                },
            },
        ],
        fields: [
            {
                name: 'title',
                type: 'string',
                validationRules: 'required',
                isNullable: false,
            },
        ],
        gropName: '',
    },
    {
        name: 'Like',
        apiIdSingular: 'like',
        apiIdPlural: 'likes',
        groupName: '',
        relations: [
            {
                relationType: null,
                relationTable: null,
                isOneToMany: false,
                isManyToMany: false,
                isParent: true,
                isChild: false,
                parent: {
                    name: 'Like',
                    apiIdSingular: 'like',
                    apiIdPlural: 'likes',
                    groupName: '',
                    method: 'hasMany',
                },
                child: {
                    method: 'belongsTo',
                },
            },
            {
                relationType: {
                    name: 'One to Many',
                    code: 'one-to-many',
                },
                relationTable: {
                    name: 'Post',
                    apiIdSingular: 'post',
                    apiIdPlural: 'posts',
                    groupName: '',
                    child: {
                        name: 'Like',
                        apiIdSingular: 'like',
                        apiIdPlural: 'likes',
                        groupName: '',
                    },
                    parent: {
                        name: 'Post',
                        apiIdSingular: 'post',
                        apiIdPlural: 'posts',
                        groupName: '',
                    },
                    isOneToMany: true,
                    isManyToMany: false,
                    isChild: true,
                    isParent: false,
                },
            },
        ],
        fields: [],
        gropName: '',
    },
    {
        name: 'Comment',
        apiIdSingular: 'comment',
        apiIdPlural: 'comments',
        groupName: '',
        relations: [
            {
                relationType: null,
                relationTable: null,
                isOneToMany: false,
                isManyToMany: false,
                isParent: true,
                isChild: false,
                parent: {
                    name: 'Comment',
                    apiIdSingular: 'comment',
                    apiIdPlural: 'comments',
                    groupName: '',
                    method: 'hasMany',
                },
                child: {
                    method: 'belongsTo',
                },
            },
            {
                relationType: {
                    name: 'One to Many',
                    code: 'one-to-many',
                },
                relationTable: {
                    name: 'Post',
                    apiIdSingular: 'post',
                    apiIdPlural: 'posts',
                    groupName: '',
                    child: {
                        name: 'Comment',
                        apiIdSingular: 'comment',
                        apiIdPlural: 'comments',
                        groupName: '',
                    },
                    parent: {
                        name: 'Post',
                        apiIdSingular: 'post',
                        apiIdPlural: 'posts',
                        groupName: '',
                    },
                    isOneToMany: true,
                    isManyToMany: false,
                    isChild: true,
                    isParent: false,
                },
            },
        ],
        fields: [
            {
                name: 'title',
                type: 'longText',
                validationRules: '',
                isNullable: true,
            },
        ],
        gropName: '',
    },
    {
        name: 'Post',
        apiIdSingular: 'post',
        apiIdPlural: 'posts',
        groupName: '',
        relations: [
            {
                relationType: {
                    name: 'One to Many',
                    code: 'one-to-many',
                },
                relationTable: {
                    name: 'Comment',
                    apiIdSingular: 'comment',
                    apiIdPlural: 'comments',
                    groupName: '',
                    relations: [
                        {
                            relationType: null,
                            relationTable: null,
                            isOneToMany: false,
                            isManyToMany: false,
                            isParent: true,
                            isChild: false,
                            parent: {
                                name: 'Comment',
                                apiIdSingular: 'comment',
                                apiIdPlural: 'comments',
                                groupName: '',
                                method: 'hasMany',
                            },
                            child: {
                                method: 'belongsTo',
                            },
                        },
                        {
                            relationType: {
                                name: 'One to Many',
                                code: 'one-to-many',
                            },
                            relationTable: {
                                name: 'Post',
                                apiIdSingular: 'post',
                                apiIdPlural: 'posts',
                                groupName: '',
                                child: {
                                    name: 'Comment',
                                    apiIdSingular: 'comment',
                                    apiIdPlural: 'comments',
                                    groupName: '',
                                },
                                parent: {
                                    name: 'Post',
                                    apiIdSingular: 'post',
                                    apiIdPlural: 'posts',
                                    groupName: '',
                                },
                                isOneToMany: true,
                                isManyToMany: false,
                                isChild: true,
                                isParent: false,
                            },
                        },
                    ],
                    fields: [
                        {
                            name: 'title',
                            type: 'longText',
                            validationRules: '',
                            isNullable: true,
                        },
                    ],
                    gropName: '',
                },
                isOneToMany: true,
                isManyToMany: false,
                isParent: true,
                isChild: false,
                parent: {
                    name: 'Post',
                    apiIdSingular: 'post',
                    apiIdPlural: 'posts',
                    groupName: '',
                },
                child: {
                    name: 'Comment',
                    apiIdSingular: 'comment',
                    apiIdPlural: 'comments',
                    groupName: '',
                },
            },
            {
                relationType: {
                    name: 'One to Many',
                    code: 'one-to-many',
                },
                relationTable: {
                    name: 'Like',
                    apiIdSingular: 'like',
                    apiIdPlural: 'likes',
                    groupName: '',
                    relations: [
                        {
                            relationType: null,
                            relationTable: null,
                            isOneToMany: false,
                            isManyToMany: false,
                            isParent: true,
                            isChild: false,
                            parent: {
                                name: 'Like',
                                apiIdSingular: 'like',
                                apiIdPlural: 'likes',
                                groupName: '',
                                method: 'hasMany',
                            },
                            child: {
                                method: 'belongsTo',
                            },
                        },
                        {
                            relationType: {
                                name: 'One to Many',
                                code: 'one-to-many',
                            },
                            relationTable: {
                                name: 'Post',
                                apiIdSingular: 'post',
                                apiIdPlural: 'posts',
                                groupName: '',
                                child: {
                                    name: 'Like',
                                    apiIdSingular: 'like',
                                    apiIdPlural: 'likes',
                                    groupName: '',
                                },
                                parent: {
                                    name: 'Post',
                                    apiIdSingular: 'post',
                                    apiIdPlural: 'posts',
                                    groupName: '',
                                },
                                isOneToMany: true,
                                isManyToMany: false,
                                isChild: true,
                                isParent: false,
                            },
                        },
                    ],
                    fields: [],
                    gropName: '',
                },
                isOneToMany: true,
                isManyToMany: false,
                parent: {
                    name: 'Post',
                    apiIdSingular: 'post',
                    apiIdPlural: 'posts',
                    groupName: '',
                },
                child: {
                    name: 'Like',
                    apiIdSingular: 'like',
                    apiIdPlural: 'likes',
                    groupName: '',
                },
                isParent: true,
                isChild: false,
            },
        ],
        fields: [
            {
                name: 'title',
                type: 'longText',
                validationRules: 'required',
                isNullable: false,
            },
            {
                name: 'description',
                type: 'longText',
                validationRules: 'required',
                isNullable: false,
            },
            {
                name: 'content',
                type: 'longText',
                validationRules: 'required',
                isNullable: false,
            },
        ],
    },
    {
        name: 'Skill',
        apiIdSingular: 'skill',
        apiIdPlural: 'skills',
        groupName: '',
        relations: [
            {
                relationType: {
                    name: 'Many to Many',
                    code: 'many-to-many',
                },
                relationTable: {
                    name: 'Developer',
                    apiIdSingular: 'developer',
                    apiIdPlural: 'developers',
                    groupName: '',
                    relations: [
                        {
                            relationType: null,
                            relationTable: null,
                            isOneToMany: false,
                            isManyToMany: false,
                            isParent: true,
                            isChild: false,
                            parent: {
                                name: 'Developer',
                                apiIdSingular: 'developer',
                                apiIdPlural: 'developers',
                                groupName: '',
                                method: 'hasMany',
                            },
                            child: {
                                method: 'belongsTo',
                            },
                        },
                        {
                            relationType: {
                                name: 'Many to Many',
                                code: 'many-to-many',
                            },
                            relationTable: {
                                name: 'Skill',
                                apiIdSingular: 'skill',
                                apiIdPlural: 'skills',
                                groupName: '',
                            },
                            child: {
                                name: 'Developer',
                                apiIdSingular: 'developer',
                                apiIdPlural: 'developers',
                                groupName: '',
                                method: 'belongsTo',
                            },
                            parent: {
                                name: 'Skill',
                                apiIdSingular: 'skill',
                                apiIdPlural: 'skills',
                                groupName: '',
                                method: 'hasMany',
                            },
                            isOneToMany: false,
                            isManyToMany: true,
                            isChild: true,
                            isParent: false,
                        },
                    ],
                    fields: [
                        {
                            name: 'fullName',
                            type: 'string',
                            validationRules: 'required',
                            isNullable: false,
                        },
                    ],
                },
                isOneToMany: false,
                isManyToMany: true,
                isParent: true,
                isChild: false,
                parent: {
                    name: 'Skill',
                    apiIdSingular: 'skill',
                    apiIdPlural: 'skills',
                    groupName: '',
                    method: 'hasMany',
                },
                child: {
                    name: 'Developer',
                    apiIdSingular: 'developer',
                    apiIdPlural: 'developers',
                    groupName: '',
                    method: 'belongsTo',
                },
            },
        ],
        fields: [
            {
                name: 'title',
                type: 'string',
                validationRules: 'required',
                isNullable: false,
            },
        ],
        gropName: '',
    },
    {
        name: 'Developer',
        apiIdSingular: 'developer',
        apiIdPlural: 'developers',
        groupName: '',
        relations: [
            {
                relationType: null,
                relationTable: null,
                isOneToMany: false,
                isManyToMany: false,
                isParent: true,
                isChild: false,
                parent: {
                    name: 'Developer',
                    apiIdSingular: 'developer',
                    apiIdPlural: 'developers',
                    groupName: '',
                    method: 'hasMany',
                },
                child: {
                    method: 'belongsTo',
                },
            },
            {
                relationType: {
                    name: 'Many to Many',
                    code: 'many-to-many',
                },
                relationTable: {
                    name: 'Skill',
                    apiIdSingular: 'skill',
                    apiIdPlural: 'skills',
                    groupName: '',
                },
                child: {
                    name: 'Developer',
                    apiIdSingular: 'developer',
                    apiIdPlural: 'developers',
                    groupName: '',
                    method: 'belongsTo',
                },
                parent: {
                    name: 'Skill',
                    apiIdSingular: 'skill',
                    apiIdPlural: 'skills',
                    groupName: '',
                    method: 'hasMany',
                },
                isOneToMany: false,
                isManyToMany: true,
                isChild: true,
                isParent: false,
            },
        ],
        fields: [
            {
                name: 'fullName',
                type: 'string',
                validationRules: 'required',
                isNullable: false,
            },
        ],
    },
]
